FROM frjaraur/nettools:small
CMD ["/help"]
USER root
ENV JMETERVERSION="3.3"
ENV PATH=${PATH}:/usr/local/jmeter/bin
RUN apk add --no-cache --update \
openjdk8-jre \
&& rm -rf /var/cache/apk/* \
&& curl -sL -o /tmp/jmeter.tgz http://apache.rediris.es//jmeter/binaries/apache-jmeter-${JMETERVERSION}.tgz \
&& cd /usr/local \
&& tar -zxf /tmp/jmeter.tgz \
&& ln -s apache-jmete* jmeter
USER 65500
