FROM loadimpact/k6 as k6

FROM alpine
RUN apk add --no-cache --update bash \
curl \
apache2-utils \
netcat-openbsd \
nmap-nping \
nmap bind-tools \
python3 \
ca-certificates \
&& pip3 install --upgrade pip \
&& pip3 install httpie httpie-unixsocket \
httping \
&& rm -rf /var/cache/apk/* \
&& adduser -D -H -u 65500 nettools

COPY --from=k6 /root/k6 /usr/local/bin
COPY --from=k6 /etc/ssl /etc/ssl
COPY help /help

CMD ["/help"]

USER 65500
