#!/bin/sh
ToolsAvailable(){
    printf "Tools Available ins Small Version:\n-curl\n-ab\n-netcat\n-nping\n-nslookup\n-dig\n-host\n-http (httping)\n-httpstat"
    printf "Tools Available in Jmeter, K6 or Everything:\n-jmeter\n-k6\n-both\n"
}

Examples(){
        printf "HTTP:\nhttp --follow --verbose --headers www.codegazers.org\n"

}

ToolsAvailable
